name: Our Steps
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      
      - id: set-foo
      # run: echo "(name)=(value)" >> (ENV_VAR)
        run: echo "foo=bar" >> @GITHUB_OUTPUT
      # - run: echo ${{ steps.<step_id>.outputs.foo }}
      - run: echo ${{ steps.set-foo.outputs.foo }}
